- README.md
- clients/cache/disk_cache.go
- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
- clients/nacos_client/nacos_client.go
- clients/naming_client/host_reator.go
- clients/naming_client/naming_client.go
- common/constant/config.go
- common/constant/const.go
- common/logger/logger.go
- common/util/file.go
- example/main/main.go
- utils/common.go
1、support log to file   and logfile rotate
2、support config cache in file
> Feature cache log

- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
- clients/config_client/config_proxy.go
- common/constant/config.go
- common/constant/const.go
- common/nacos_error/nacos_error.go
- common/nacos_server/nacos_server.go
- example/main/main.go
- utils/common.go
> fix bug of issue #9

- clients/naming_client/host_reator.go
- clients/naming_client/naming_client.go
- clients/naming_client/naming_client_interface.go
- clients/naming_client/naming_proxy.go
- common/constant/const.go
- vo/service_param.go
related to nacos PR - https://github.com/alibaba/nacos/pull/1486
> Add api of getting All Services

- common/nacos_server/nacos_server.go
> change GBK encode to UTF8

- common/nacos_server/nacos_server.go
- go.mod
- go.sum
修复 https://github.com/satori/go.uuid/issues/106
Signed-off-by: fuling <fuling.lgz@alibaba-inc.com>
> [升级] satori/go.uuid： 1.2.0 升级到 1.2.1

- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
- go.sum
- vo/config_param.go
add cancel listen config  func
> add cancel listen config  func

- clients/naming_client/host_reator.go
- clients/naming_client/naming_client.go
- clients/naming_client/naming_client_test.go
- clients/naming_client/naming_proxy.go
- vo/service_param.go
fix https://github.com/nacos-group/nacos-sdk-go/issues/78
> Get sevice list

- clients/naming_client/beat_reactor_test.go
- clients/naming_client/naming_client_test.go
- go.sum
Fix the Naming Client to run all the tests.
> Fix naming client test

- common/nacos_server/nacos_server.go
> FEA(star.xie)nacos-sdk-go/common/:getconfig or putconfig 请求适配协议头https

- NOTICE
- clients/cache/concurrent_map.go
> add preservation of copyright and license notices

- README.md
- README_CN.md
为readme.md和README_CN.md规整了格式，修正部分单词错误
> Fix: Format readme.md and README_CN.md

- vo/service_param.go
Remove RegisterInstanceParam and DeregisterInstanceParam tenant
> [#109]Remove register instance param tenant

- clients/config_client/config_client_test.go
- common/http_agent/post.go
- util/common.go
> encode params before post method

- clients/config_client/config_client.go
- clients/config_client/config_proxy.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/135
> Listening configuration increases the namespace

- clients/naming_client/host_reator.go
- clients/naming_client/push_receiver.go
- common/constant/const.go
Fixes #141 
Subscribe may be called when PushRecevier is initialling.
So initial it first then listening asynchronously.
> Fix  go client is not show in the service subscription list

- util/common.go
The LocalIP() method will get lo:1's IP address
> filter loopback ip

- clients/config_client/config_client.go
Count the number of listeners using Concurrentmap.count
> Count the number of listeners using Concurrentmap.count

- clients/config_client/config_client.go
FIX: https://github.com/nacos-group/nacos-sdk-go/issues/166
> Fix the issue of incorrect err display in ListenConfig.

- clients/config_client/config_client_test.go
获取当前golang版本，对data id 进行拼接，保证不同版本同时运行测试的时候，不会存在操作同一个key
fix #172
> fix 172, when multiple versions are testing at the same time.

- README.md
- README_CN.md
- clients/client_factory.go
- clients/client_factory_test.go
- example/config/main.go
- example/service/main.go
- vo/client_param.go
> 154 client factory params change to options

- clients/config_client/config_client_test.go
> fix ut of test_searchConfig

- clients/config_client/config_client_test.go
> refine Test_SearchConfig.

- common/http_agent/put.go
> delete std log when http_agent put err

- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
remove the return error when not find the config.
Fixes #209
> [BUG 209] remove the return error when not find the config

- common/nacos_server/nacos_server.go
- common/security/security_proxy.go
> 当认证不通过时，创建client返 回成功(主要兼容nacos挂掉的情况)

- util/common.go
- util/common_test.go
> fix:因获取local ip错误导致无法接收到sever的udp包 (#208)

- clients/client_factory.go
- clients/config_client/config_client.go
- clients/config_client/config_client_interface.go
- clients/config_client/config_proxy.go
- clients/nacos_client/nacos_client.go
- clients/naming_client/naming_client.go
- common/constant/config.go
- common/constant/const.go
- common/nacos_server/nacos_server.go
- common/remote/rpc/grpc_client.go
- common/remote/rpc/grpc_connection.go
- common/remote/rpc/rpc_client.go
- common/remote/rpc/rpc_request/config_request.go
- common/remote/rpc/rpc_response/config_response.go
- common/remote/rpc/rpc_response/naming_response.go
- common/remote/rpc/rpc_response/rpc_response.go
- common/remote/rpc/server_request_handler.go
- model/config.go
- util/content.go
- vo/config_param.go
2.0.0
fix:https://github.com/nacos-group/nacos-sdk-go/issues/234
> config client support GRPC 

- example/config/main.go
- example/service/main.go
update 2.0.0 example
fix:https://github.com/nacos-group/nacos-sdk-go/issues/235
> update 2.0.0 example

- clients/client_factory.go
- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
fix：https://github.com/nacos-group/nacos-sdk-go/issues/250
The scheduling task is started when the Config Client is created.
> remove init to start the scheduling task

- clients/client_factory.go
- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
- clients/config_client/config_proxy.go
- clients/config_client/config_proxy_interface.go
- clients/naming_client/naming_client.go
- clients/naming_client/naming_client_test.go
- common/remote/rpc/connection_test.go
- common/remote/rpc/rpc_response/naming_response.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/233
> update naming&config ut

- clients/naming_client/naming_client.go
- clients/naming_client/naming_instance_chooser.go
> fix instance chooser

- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
经测试，`ListenConfig`timeout是因为获取配置后未urldecode
另外测试，dataId和group应该是不支持中文的，请问是否需要支持上
> Fixes #222, for the char is not urldecode

- clients/config_client/config_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/270
> fix:270 ListenConfig func() cache not pointer

- README.md
- README_CN.md
> doc: refresh v2.0 doc

- clients/config_client/config_client.go
- clients/nacos_client/nacos_client.go
- clients/naming_client/naming_client.go
- common/constant/client_config_options.go
- common/constant/client_config_options_test.go
- common/constant/config.go
- common/logger/logger.go
> Add log sampling support

- clients/naming_client/naming_client.go
- clients/naming_client/naming_client_interface.go
- clients/naming_client/naming_client_test.go
- clients/naming_client/naming_proxy.go
- go.sum
- vo/service_param.go
> Add function UpdateInstance() #286

- clients/config_client/config_client_test.go
- vo/config_param.go
> support config type

- clients/naming_client/beat_reactor.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/292
Before adding a heartbeat, check whether it already exists. If yes, stop the heartbeat and clear the cache
> fix AddBeatInfo func goroutine leak

- common/file/file.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/302
> Optimizing folder creation

- .gitignore
- clients/config_client/config_client.go
> optimize code

- README.md
- README_CN.md
> update 2.x readme

- clients/config_client/config_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/311
>  scheduler delay is 500 ms

- clients/config_client/config_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/304
> update get config log level

- common/nacos_server/nacos_server.go
Error requesting nacos server, returned to caller
> refine req server error log

- clients/naming_client/naming_grpc/connection_event_listener.go
- go.sum
> [ISSUE #249] Remove the sets in connection event lister

- clients/naming_client/host_reactor.go
- clients/naming_client/host_reactor_test.go
- clients/naming_client/naming_client_test.go
- clients/naming_client/naming_proxy.go
> refine code

- clients/naming_client/naming_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/331
> add pageNo&pageSize default value

- clients/config_client/config_client_test.go
- clients/naming_client/beat_reactor.go
- clients/naming_client/beat_reactor_test.go
- clients/naming_client/naming_client.go
- clients/naming_client/naming_client_test.go
- clients/naming_client/subscribe_callback_test.go
- util/common.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/328
> deep copy matedata map

- common/remote/rpc/rpc_client.go
> pre end loop.

- example/service/main.go
fix：https://github.com/nacos-group/nacos-sdk-go/issues/362
> update example subscribeParam

- clients/naming_client/beat_reactor.go
- clients/naming_client/naming_proxy.go
Resolves #370
更新函数参数，避免值拷贝，解决race
> fix race in naming_client

- clients/config_client/config_client.go
> fix a panic when requestProxy returns a nil response response when calling PublishConfig

- clients/naming_client/subscribe_callback.go
- model/service.go
add healthy for model.SubscribeService
> add healthy for subscribe struct

- clients/client_factory.go
- clients/client_factory_test.go
- clients/config_client/config_client.go
- clients/nacos_client/nacos_client.go
- clients/naming_client/naming_client.go
- common/constant/client_config_options.go
- common/constant/client_config_options_test.go
- common/constant/config.go
- common/constant/const.go
- common/logger/logger.go
- common/logger/logger_test.go
- example/config/main.go
- example/service/main.go
- go.mod
- go.sum
fix:https://github.com/nacos-group/nacos-sdk-go/issues/360
> add lumberjack logs can be divided by size and time

- common/remote/rpc/connection.go
- common/remote/rpc/grpc_client.go
- common/remote/rpc/grpc_connection.go
Close the old streamClient recv goroutine
> close stream client

- clients/naming_client/naming_grpc/naming_grpc_proxy.go
- common/constant/client_config_options.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/319
> subscribe add appname

- clients/config_client/config_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/316
> ignore cache content

- clients/cache/disk_cache.go
- clients/naming_client/naming_cache/service_info_holder.go
- clients/naming_client/naming_http/beat_reactor.go
- clients/naming_client/naming_http/push_receiver.go
- common/logger/logger.go
- common/remote/rpc/rpc_client.go
- go.mod
- go.sum
fix:https://github.com/nacos-group/nacos-sdk-go/issues/394
> sync semaphore

- clients/config_client/config_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/402
> config listen execute max chan

- clients/naming_client/naming_http/push_receiver.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/412
> refine push receiver start server

- clients/naming_client/push_receiver.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/412
> refine push receiver start udp

- common/remote/rpc/rpc_client.go
> change to warn log level

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
> add issue template

- clients/config_client/config_proxy.go
- clients/naming_client/naming_grpc/naming_grpc_proxy.go
- common/nacos_server/nacos_server.go
- common/remote/rpc/rpc_client.go
- common/remote/rpc/server_request_handler.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/428 , https://github.com/nacos-group/nacos-sdk-go/issues/356 , https://github.com/nacos-group/nacos-sdk-go/issues/230
> support sk ak

- clients/naming_client/naming_cache/service_info_holder.go
- clients/naming_client/naming_cache/service_info_holder_test.go
change the way of compare instance.
see #419 .
this is for v2.X to fix bug #285
> Change the way of compare service hosts.

- .github/workflows/go.yml
fix:https://github.com/nacos-group/nacos-sdk-go/issues/440
> ci add race check

- common/remote/rpc/grpc_client.go
- common/remote/rpc/rpc_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/447
> fix lastActiveTimestamp race

- .github/workflows/go.yml
- README.md
- README_CN.md
- common/constant/config.go
- common/constant/server_config_options.go
- common/nacos_server/nacos_server.go
- common/remote/rpc/grpc_client.go
- common/remote/rpc/rpc_client.go
- common/remote/rpc/rpc_request/config_request.go
- common/remote/rpc/rpc_request/rpc_request.go
close https://github.com/nacos-group/nacos-sdk-go/issues/455
> feat: server config support custom grpc port

- clients/cache/disk_cache.go
- clients/cache/disk_cache_test.go
- clients/config_client/config_client.go
- common/constant/const.go
- common/file/file.go
feature.Use local failover file content first when try to get config.
> feature.Use local failover file content first when try to get config.

- clients/config_client/config_client.go
fix: https://github.com/nacos-group/nacos-sdk-go/issues/470
> fix config cache path

- clients/naming_client/naming_http/push_receiver.go
https://github.com/nacos-group/nacos-sdk-go/issues/471
> optimize PushReceiver. startServer

- clients/naming_client/naming_grpc/naming_grpc_proxy.go
- common/nacos_server/nacos_server.go
- common/remote/rpc/rpc_request/naming_request.go
- common/remote/rpc/rpc_request/rpc_request.go
implement the same logic as java client
> Support ram auth for naming request

- clients/naming_client/naming_cache/service_info_holder.go
- clients/naming_client/naming_cache/service_info_holder_test.go
> not use the point of service to check service is changed or not.

- clients/naming_client/naming_cache/service_info_holder.go
- clients/naming_client/naming_proxy_delegate.go
- clients/naming_client/service_info_updater.go
- common/remote/rpc/grpc_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/421
> replace service_info_holder concurrent map with sync.map

- common/remote/rpc/grpc_client.go
Fix the problem for https://github.com/alibaba/nacos/pull/9013
refer to above https://github.com/alibaba/nacos/pull/9017
> enhance grpc time out

- clients/config_client/config_client.go
- clients/config_client/config_client_test.go
- clients/config_client/config_proxy.go
- clients/config_client/config_proxy_interface.go
- clients/config_client/limiter.go
- clients/config_client/limiter_test.go
- clients/naming_client/naming_client.go
- clients/naming_client/naming_grpc/naming_grpc_proxy.go
- clients/naming_client/naming_http/beat_reactor.go
- clients/naming_client/naming_http/beat_reactor_test.go
- clients/naming_client/naming_http/naming_http_proxy.go
- clients/naming_client/naming_http/push_receiver.go
- clients/naming_client/naming_proxy_delegate.go
- clients/naming_client/service_info_updater.go
- common/nacos_server/nacos_server.go
- common/remote/rpc/grpc_client.go
- common/remote/rpc/rpc_client.go
- common/security/security_proxy.go
fix: https://github.com/nacos-group/nacos-sdk-go/issues/517 , https://github.com/nacos-group/nacos-sdk-go/issues/513
> use context cancel leak goroutine

- common/constant/config.go
change "gorutine" to "goroutine"
> chore: fix typo

- clients/naming_client/naming_grpc/connection_event_listener.go
- clients/naming_client/naming_grpc/naming_grpc_proxy.go
- clients/naming_client/naming_proxy_delegate.go
修复当NotLoadCacheAtStart设置为false,第二次启动，服务订阅Subscribe不生效问题
> fix issue #519

- clients/config_client/config_client_test.go
- clients/naming_client/host_reactor.go
- clients/naming_client/naming_client.go
- go.mod
- go.sum
fix:https://github.com/nacos-group/nacos-sdk-go/issues/508
> fix GetAllServiceInfo error

- README_CN.md
> fix error in example code

- clients/config_client/config_client.go
- util/md5.go
fixes:https://github.com/nacos-group/nacos-sdk-go/issues/550
> fix config listener cpu usage

- clients/naming_client/beat_reactor.go
- common/constant/const.go
fixes:https://github.com/nacos-group/nacos-sdk-go/issues/556
> fix add beat info

- README.md
> update README go format

- common/remote/rpc/grpc_client.go
fixes:https://github.com/nacos-group/nacos-sdk-go/issues/567
> refine grpc_client

- common/remote/rpc/rpc_client.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/576
> fix panic for rpc errorResponse

- clients/naming_client/naming_grpc/naming_grpc_proxy.go
- common/remote/rpc/rpc_request/naming_request.go
- example/service/main.go
- vo/service_param.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/524
> fix QueryInstancesOfService clusters

- clients/config_client/config_client.go
fix:https://github.com/alibaba/nacos/issues/10222
> fix read config cache

- clients/config_client/config_client.go
- clients/config_client/config_proxy.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/640
> fix cacheData race

- clients/cache/disk_cache.go
- clients/cache/disk_cache_test.go
- clients/naming_client/naming_http/push_receiver.go
- common/http_agent/http_agent.go
- common/nacos_server/nacos_server.go
- common/security/security_proxy.go
- common/tls/tls.go
- common/tls/tls_test.go
> refactor: move from ioutil to io packages

- common/constant/const.go
Update go client version to 2.2.4
> Update go client version to 2.2.4

- common/encryption/handler.go
- common/encryption/kms_client.go
- common/encryption/kms_plugins.go
- common/filter/config_encryption_filter.go
- common/filter/config_filter.go
> [bug fix] fix up encryption logger level to debug mod

- common/remote/rpc/rpc_request/rpc_request.go
check if the headers are nil before iput all headers to request.
> fix panic when server push request has request headers.

- clients/naming_client/naming_grpc/connection_event_listener.go
- common/constant/const.go
refine redo subscribe ,fix:https://github.com/nacos-group/nacos-sdk-go/issues/753
> refine redo subscribe

- clients/cache/disk_cache.go
- common/constant/const.go
fix:https://github.com/nacos-group/nacos-sdk-go/issues/762
> update getFailOverConfig log level

- clients/config_client/config_client.go
- vo/config_param.go
Support publish config with config_tags, add ConfigTags in ConfigParam
> Support publish config with config_tags

- common/constant/const.go
NotifySubscriberRequest name should be NotifySubscriberRequest，not NotifySubscribeRequest
> fix error request type name

- common/security/nacos_auth_client.go
- common/security/nacos_auth_client_test.go
fix(#807 ): since the program will only log in once, there is no way to refresh the token.
> fix(#807 ): since the program will only log in once, there is no way to refresh the token.

- clients/naming_client/naming_cache/subscribe_callback.go
- clients/naming_client/naming_cache/subscribe_callback_test.go
- clients/naming_client/naming_client.go
- clients/naming_client/naming_client_test.go
> fix: nacos client unsubscribe
