nacos-group/nacos-sdk-go

clients/naming_client/host_reator.go

it is a bug, if I call naming.Subscribe( callback ) ，and in the callback I call GetService will always get last old data.
e.g
```go
func(services []model.SubscribeService, err error){
for _, service := range services {
// ps this updatedService is old 
updatedService, err := np.namingClient.GetService(vo.GetServiceParam{
[]string{service.clusterName},
service.serviceName,
})
} 
}
```
because notify service changed is always before set `serviceInfoMap`

fix: update service before subscribe callback

---

clients/naming_client/push_receiver.go

It is weird and dangerous to invoke the os.Exit() as a Middleware.

It is weird and dangerous to invoke the os.Exit() as a Middleware.

---

clients/config_client/config_client.go
clients/config_client/config_client_test.go
clients/nacos_client/nacos_client.go
clients/naming_client/naming_client_test.go
example/config/main.go
example/service/main.go

#49 fix not notify change when listen config

fix listen config not notify change

---

clients/naming_client/naming_client.go

注册服务时如果没有设置元数据，默认值将会是 nil，这会导致 Spring boot 网关启动时报错。
我注册服务时的配置：
网关的报错：

服务注册时给 Metadata 设置默认值

---

clients/config_client/config_client.go

优化使用Concurrentmap.count计算监听者数量。
fix:https://github.com/nacos-group/nacos-sdk-go/issues/157

Count the number of listeners using Concurrentmap.count

---

common/nacos_server/nacos_server.go

Fix: missing udpPort when send beat info & lose server config scheme when called refreshServerIfNeed

Fix server config scheme missing

---

README.md
README_CN.md
clients/config_client/config_client_test.go
clients/naming_client/naming_client_test.go
common/constant/client_config_options.go
common/constant/client_config_options_test.go
common/constant/server_config_options.go
common/constant/server_config_options_test.go
example/config/main.go
example/service/main.go

Init client's params change to ...options

---

common/logger/logger.go
common/logger/logger_test.go
common/logger/logging.go

fix logger data race 
Fixes #148 
@sanxun0325

fix the logger data race

---

README_CN.md
clients/config_client/config_client_test.go
clients/naming_client/beat_reactor.go
clients/naming_client/naming_client.go
model/service.go

1、格式整理、错别字修复
2、修复注销概率发生data race的bug：使用int32的原子操作控制状态，避免并发读写bool导致race，也便于后续添加状态类型

Fix deregister data race(#180)

---

clients/nacos_client/nacos_client.go

When users don't set timeoutms config, we should set the default value according the comment of this config.

Fix default timeoutms config

---

clients/naming_client/naming_client.go

Currently, when the service information is cached in the local file, the callback function will not be triggered when we call the subscribe method. So we should trigger a callback when subscribe is called.

Trigger callback when subscribe service

---

clients/naming_client/naming_client.go

#201 
当 nacos 服务端版本低于 1.3.x 时,空服务名会导致 nacos 实例异常. 服务端版本大于 1.3.x 时修复了这个问题,所以在客户端也加上判断

fix: 当服务名称为空时导致 nacos 服务异常的问题

---

README.md
README_CN.md
common/constant/config.go

fix issue:https://github.com/nacos-group/nacos-sdk-go/issues/191
Blank characters should be set when the namespace is public

Add namespace value description

---

clients/client_factory.go

refine SetClientConfig
Timeoutms and BeatInterval are configured by default in SetClientConfig func.

refine SetClientConfig

---

clients/cache/disk_cache.go
clients/cache/disk_cache_test.go
common/constant/const.go

修复 https://github.com/nacos-group/nacos-sdk-go/issues/204 问题

fix:修复windows文件名称问题

---

clients/naming_client/push_receiver.go

When connection has not been established, close it directly would cause nil pointer exception.

fix nil pointer exception bug

---

clients/naming_client/naming_client.go

The same seed in rand.seed will result in the same random number。rand.seed should be initialized once where necessary

fixed duplicate random numbers

---

clients/config_client/config_client.go

当使用多个namespceId建立客户端监听配置变化时，在此处clientConfig已经不与v对应，cacheMap.Set会造成的缓存异常。

Repair the cache pollution caused by v.tenat != clientConfig.NamespaceId

---

clients/naming_client/naming_cache/service_info_holder.go

Initialize Serviceinfomap whether or not local cache is loaded

fix bug 267

---

clients/naming_client/naming_grpc/connection_event_listener.go

What type of PR is this?
/kind bug
What this PR does / why we need it:
redoRegisterEachService will cause servicename and groupname to swap
https://github.com/alibaba/nacos/issues/6232
Which issue(s) this PR fixes:
Fixes #276
Special notes for your reviewer:
@sanxun0325
Does this PR introduce a user-facing change?
> No
Additional documentation e.g., usage docs, etc.:
> No

bugfix: redoRegisterEachService function to get servicename and groupname error

---

clients/naming_client/naming_client.go

In the master branch, INacosClient in NamingClient is not initialized. We should initialize it as we did in v2.
Ref: https://github.com/nacos-group/nacos-sdk-go/blob/2.0.0/clients/naming_client/naming_client.go#L44

fix: init NamingClient.INacosClient

---

go.mod
go.sum

CVE-2020-10675
moderate severity
Vulnerable versions: < 1.0.0
Patched version: 1.0.0
The Library API in buger jsonparser through 2019-12-04 allows attackers to cause a denial of service (infinite loop) via a Delete call.

deps: upgrade jsonparser

---

clients/naming_client/naming_grpc/connection_event_listener.go
clients/naming_client/naming_grpc/naming_grpc_proxy.go

If send rpc request failed, it won't cache subscribe info.  when reconnect, it's won't resubscribe again.
So cache subscribe info firstly, then send rpc request.

fix reconnect can't subscribe problem.

---

clients/config_client/config_client.go

Currently when [`NewConfigProxy`](https://github.com/nacos-group/nacos-sdk-go/blob/2.0.0/clients/config_client/config_client.go#L100) returns an error , `NewConfigClient` just ignored it which may cause unexpected error. 
For example, an I/O timeout error in the login method, and the next request will fail due to the lack of accessToken.

bugfix: throw NewConfigProxy error

---

common/remote/rpc/grpc_client.go
common/remote/rpc/rpc_client.go
common/remote/rpc/server_request_handler.go

this pull request solved the issue #325 and fix a code bug when using lock
the cause of issue #325 is:
when the nacos server startup, it need a while to get ready to serve request.  if a request going to the server in this period, the server whill return 3xx.  this cause the client healthCheck failed and cause the client get a connection to the server failed.

client automatically re-registers

---

clients/client_factory.go
common/constant/client_config_options.go
common/constant/config.go
common/constant/const.go
common/constant/server_tls_options.go
common/constant/server_tls_options_test.go
common/http_agent/delete.go
common/http_agent/get.go
common/http_agent/http_agent.go
common/http_agent/put.go
common/tls/tls.go
common/tls/tls_test.go

**purpose**
issue #259
**changelog:**
add tls.go to provide tls configuration (also applicable to grpc)
**others:**
after this part is passed, filewatcher can be added to monitor tls file change

support tls

---

clients/config_client/config_client.go
clients/naming_client/naming_client.go
common/constant/client_config_options.go
common/constant/config.go
common/logger/logger.go
example/config/main.go
example/service/main.go

https://github.com/apache/dubbo-go/issues/1960
fix:https://github.com/nacos-group/nacos-sdk-go/issues/490

bugfix dubbo-go issue: nacos-go-sdk stdout redirect #1960

---

clients/config_client/config_client.go

fix: fix ConfigClient data race

---

clients/config_client/config_client_test.go
clients/config_client/config_proxy.go
clients/config_client/limiter.go
clients/config_client/limiter_test.go
go.mod
go.sum

Add limiter for config request to avoid dealing too much GetConfig request in nacos-server.
The trial limiter configuration is allow 5 request per second,and max reserver stock is 5 too.which is the same as Java nacos client.

feature.add limiter for config client.

---

clients/naming_client/naming_http/beat_reactor.go
clients/naming_client/naming_http/naming_http_proxy.go
common/nacos_server/nacos_server.go
common/nacos_server/nacos_server_test.go

[ISSUE #537] Fix naming http client authentication.

---

model/config.go

在 1.2.1 及以下版本中，接口返回 ConfigItem.Id 是数字类型, 而 SDK 中是 string 类型。修复 SDK 与部分低版本 Nacos 服务接口不兼容的问题。

fix: update ConfigItem.Id type to be compatible with Nacos v1.2 server

---

clients/config_client/config_client.go

`math.MaxInt64` is untyped constant. This causes overflow on a 32-bit system.
Reproduce:
```bash
$ GOARCH=arm go build example/config/main.go 
go: downloading golang.org/x/net v0.0.0-20210525063256-abc453219eb5
go: downloading golang.org/x/sys v0.0.0-20220114195835-da31bd327af9
go: downloading golang.org/x/text v0.3.6
clients\config_client\config_client.go:141:45: math.MaxInt64 (untyped int constant 9223372036854775807) overflows int
```
Edit:
`clients\config_client\config_client.go:141:45`
```go
max := int64(math.MaxInt64)
```

Fix MaxInt64 overflows on ARM 32-bits

---

clients/naming_client/service_info_updater.go
common/remote/rpc/connection.go
common/remote/rpc/grpc_client.go
common/remote/rpc/server_request_handler.go

fix: https://github.com/nacos-group/nacos-sdk-go/issues/587 , https://github.com/nacos-group/nacos-sdk-go/issues/587

update ConnectionEvent capacity

---

clients/nacos_client/nacos_client.go

https://github.com/nacos-group/nacos-sdk-go/issues/260
这个问题曾经被提到过，但是在一次次更变中又被改了回去。
go 的默认 log 是 StdErr 通道的，这条日志打印对日志收集器存在影响。
现在改为 日志等级为 info 时才打印，并且打印到 StdOut标准输出。

调整 [INFO] logDir cacheDir 日志输出

---

clients/naming_client/naming_client.go
common/constant/config.go
common/remote/rpc/server_request_handler.go

- Set success as True when ack push success.
- Same as java client, default close async update service by query.

Master sync java enhancement

---

clients/config_client/config_client.go
clients/config_client/config_client_test.go
vo/config_param.go

ConfigParam 添加 SrcUser 字段，PublishConfig 允许指定修改人。

ConfigParam add SrcUser 

---

clients/nacos_client/nacos_client.go

fix:https://github.com/nacos-group/nacos-sdk-go/issues/634
fix:https://github.com/nacos-group/nacos-sdk-go/issues/609
fix:https://github.com/nacos-group/nacos-sdk-go/pull/590

del init print log path

---

clients/config_client/config_client.go

fix:https://github.com/nacos-group/nacos-sdk-go/issues/640

refine config_client listen config

---

common/remote/rpc/rpc_client.go

[653](https://github.com/nacos-group/nacos-sdk-go/issues/653)

log it when response is fail and no error

---

clients/naming_client/naming_client.go
clients/naming_client/naming_client_interface.go

为 `INamingClient` 接口提供 `ServerHealthy() bool` 方法，便于无副作用的进行nacos服务可用性检查 fix:https://github.com/nacos-group/nacos-sdk-go/issues/676

feat: export ServerHealthy in INamingClient

---

clients/naming_client/naming_cache/subscribe_callback.go

fix: repair for updateCacheWhenEmpty not working

---

clients/cache/const.go
clients/cache/disk_cache.go
clients/cache/disk_cache_test.go
clients/config_client/config_client.go
clients/config_client/config_client_test.go
clients/config_client/config_proxy.go
common/constant/const.go
common/encryption/const.go
common/encryption/handler.go
common/encryption/kms_client.go
common/encryption/kms_plugins.go
common/filter/config_encryption_filter.go
common/filter/config_filter.go
example/config-acm/main.go
example/config-mse-kmsv3/main.go
vo/config_param_test.go

the `IConfigFilterChain` interface has only one default implementation global, and all `NacosConfigClient` instance objects depend on this global variable. That means the different `NacosConfigClient` will share the only one global variable, which will cause coupling effect to another `NacosConfigClient` when there are more than one `NacosConfigClient`.
-----
`IConfigFilterChain`接口只有一个默认的全局变量，而且不同的`NacosConfigClient`实例对象都依赖这个全局变量。这意味着不同的`NacosConfigClient`将共享唯一的一个全局变量，当有多个`NacosConfigClient`时，这将导致与另一个`NacosConfigClient`的耦合效应。

[reconstruction] change configFilterChain from public sigleton to private owned by ConfigClient

---

clients/naming_client/naming_grpc/naming_grpc_proxy.go

replace the config monitor with naming monitor in naming_grpc_proxy.

[FIX #716] fix the monitor in naming_grpc_proxy.

---

common/logger/logger.go

在创建大量 Nacos Logger 的场景下面, 会造成 Logger 的 lumberjack.Logger 出现 goroutine 大量没释放
这个 PR 是为了把Logger 做成单例

fix too many logger fault 

---

clients/naming_client/naming_cache/subscribe_callback.go

Adjust lock order to address concurrency issue  Moved defer ed.mux.Unlock() after ed.mux.Lock() to ensure immediate unlocking after acquiring the lock, resolving potential concurrency issues.

🐞 fix:Adjust lock order to address concurrency issue

---

common/logger/logger_test.go

Unit test of package`logger` failed since PR #722  merged.
It's kind of weird that a PR that failed the unit test can be merged😂...

Fix unit test failed of logger package.

---

clients/config_client/config_client_test.go
clients/config_client/config_proxy.go
clients/naming_client/naming_grpc/naming_grpc_proxy.go
common/constant/client_config_options.go
common/constant/config.go
common/remote/rpc/rpc_client.go

support app connection labels

---

common/remote/rpc/grpc_client.go
common/remote/rpc/grpc_connection.go
common/remote/rpc/server_request_handler.go

grpc add log

---

util/md5.go
util/md5_test.go

- Md5 is not empty when the content of dataId is empty, which causes high frequency calls for nacos server after dataId is deleted.

fix: md5 not empty when content is empty

---

clients/config_client/config_proxy.go
clients/naming_client/naming_grpc/connection_event_listener_test.go

- fix #795 
- An outdated unit test is commented out. It failed due to a previous commit and is difficult to modify because of the use of struct type assertions in the code.

Fix the bug of callback not triggered on client when config deleted

---

common/security/ram_auth_client.go

fix(#811): Remove error log when matched ramCredentialProvider not found

---

clients/config_client/config_connection_event_listener.go
clients/config_client/config_connection_event_listener_test.go
clients/config_client/config_proxy.go

fix(#790 ): resubscribe to previously subscribed configurations after rpcClient reconnects to the server

fix(#790): resubscribe to previously subscribed configurations after rpcClient reconnects to the serve

---

clients/config_client/config_proxy.go
model/config.go

The API for searching configurations has changed in Nacos 3.0, so version-checking logic was added to the code.

Support Nacos 3.0 Search Config
